dist: xenial

sudo: required
group: edge

#
# Test Matrix
#

language: php

env:
    global:
        - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
        - TASK_TESTS_COVERAGE=0

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

matrix:
    fast_finish: true
    include:
        - php: "7.4"
        - php: "7.3"
        - php: "7.2"
        - php: "7.1"
        - php: "7.0"
        - php: "5.6"

install:
    # install composer dependencies
    - travis_retry composer self-update
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - travis_retry composer update $DEFAULT_COMPOSER_FLAGS

before_script:
    # show some versions and env information
    - php --version
    - composer --version

    # enable code coverage
    - |
        if [ $TASK_TESTS_COVERAGE == 1 ]; then
          PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
        fi

script:
    - vendor/bin/phpunit --verbose $PHPUNIT_FLAGS

after_script:
    - |
        if [ $TASK_TESTS_COVERAGE == 1 ]; then
          travis_retry wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover coverage.clover
        fi